### ISSUE TITLE
Can we have a release with the latest changes please?

### ISSUE THREAD

**Issue by k-korn** [kovacsbalu/WazeRouteCalculator#65]
Commit https://github.com/kovacsbalu/WazeRouteCalculator/commit/a502c656320b7f72a57e40c5f3c8867b2f58b708 fixes some issues introduced by Waze API changes.  For example, Home Assistant Waze integration is currently broken (https://github.com/home-assistant/core/issues/61251) because HA uses WazeRouteCalculator==0.13 as a dependency.

Could you please release a new version of this awesome library with the latest changes included so HA bug can be fixed without hacks like manual replacement of WazeRouteCalculator?

Latest code works perfectly and needs no changes - only a new release is needed.

**Comment by Smandurlo** [comment]
It does not work perfectly, it doesn't calculate the correct time #61572

**Comment by kovacsbalu** [comment]
@Smandurlo can you please give an example?

**Comment by Smandurlo** [comment]
https://github.com/home-assistant/core/issues/61572

**Comment by fi-sch** [comment]
> home-assistant/core#61572

This is not caused by the changes that @k-korn asked to release. Your issue is probably caused by something else.

**Comment by Smandurlo** [comment]
But it is not working perfectly as stated. Why to release something that is
still buggy?

Il mar 4 gen 2022, 12:01 fi-sch ***@***.***> ha scritto:

**Comment by fi-sch** [comment]
> But it is not working perfectly as stated. Why to release something that is still buggy?

What makes you conclude that the issue is on this library's side, not Home Assistant's side?

**Comment by Smandurlo** [comment]
From A to B time is totally wrong, from B to A time is wrong, but at least
possible. HA gets the minutes from the integration, isn't it? So, if A to B
is 6 min and B to A is 1630 min, I think the problem is the one who
calculates the minutes, not the one that shows the results. But of course I
might be wrong. Anyway, there is something buggy somewhere.

Il giorno mar 4 gen 2022 alle ore 12:10 fi-sch ***@***.***>
ha scritto:

**Comment by kovacsbalu** [comment]
@Smandurlo, could you provide more accurate information about the calculated route? From - to address?
Not your own address, just some similar. I'm not using this lib in HA so I don't know how is it work.
You can clone my repo and fill example.py with your data.
Can you test with previous version also?

@k-korn 
Let me check these issues and I will release soon.

@fi-sch thanks ;)

**Comment by Smandurlo** [comment]
@kovacsbalu I will try to, but I am not that skilled with linux, so not sure I will be able to.
I can give you coordinates, I don't mind. They are "pubblic places", you can both see and rent them on airbnb and booking :-)

latitude: 42.6688309
longitude: 13.6820182

latitude: 37.138199
longitude: -7.5953

**Comment by fi-sch** [comment]
@kovacsbalu Take a peek here: https://github.com/home-assistant/core/issues/61572#issuecomment-1004742067

**Comment by Smandurlo** [comment]
I tried your code with just the cities and it works. I need to understand
how to use the coordinates :-)

***@***.***:~/WazeRouteCalculator # python3 example.py
From: Teramo, Italy - to: Cabanas de Tavira, Portugal
Start coords: (42.673004150390625, 13.739128112792969)
End coords: (37.139888763427734, -7.594666957855225)
Time 1361.15 minutes, distance 2626.32 km

Il giorno mar 4 gen 2022 alle ore 13:16 fi-sch ***@***.***>
ha scritto:

**Comment by Smandurlo** [comment]
***@***.***:~/WazeRouteCalculator # python3 example.py
From: 42.6688, 13.6820 - to: 37.1381, -7.5953
Start coords: (42.6688, 13.6820)
End coords: (37.1381, -7.5953)
Internal Error

Il giorno mar 4 gen 2022 alle ore 13:45 Felice Marra ***@***.***>
ha scritto:

**Comment by k-korn** [comment]
> Time 1361.15 minutes, distance 2626.32 km
As far as I know, Waze in general is more city-oriented and works well with routes up to couple hundreds of km. On long routes like this there may be some issues (unable to calculate the route, etc) even in Waze app itself.

For example, on the [LiveMap](https://www.waze.com/en-GB/live-map/directions?to=ll.37.1381%2C-7.5953&from=ll.42.6688%2C13.682)  this route takes 15-20 seconds for Waze servers to compute, and the response is a 3 megabyte JSON containing 3 alternate routes with 25k points each: https://i.imgur.com/mXQIN3C.png

**Comment by Smandurlo** [comment]
I checked with the app and it works, never had an issue.
The problem is not to calculate this long distance travel (it is useless),
but at the moment it shows less than 10 minutes to home and it messes up
with other automations based on short distance.

Some people will have the same problem when too far, but very close for HA.



Il mar 4 gen 2022, 16:07 Korn ***@***.***> ha scritto:

**Comment by kovacsbalu** [comment]
@k-korn, 0.14 relased :)
@Smandurlo, I will check your examples soon.

**Comment by k-korn** [comment]
Thanks!

**Comment by kovacsbalu** [comment]
@Smandurlo: probably your issue is relates to #63. 
I checked long routes and got `internal error` over 5000 road segment (size of json data). With #63  fix `AVOID_TOLL_ROADS:f` the segment number decreased from 4917 to 1911 in my longest test route.
I will cretae release 0.15 soon and you can check your route or edit the code and add `self.route_options.append('AVOID_TOLL_ROADS:f')` line to `def get_route(...` function for testing.

**Comment by Smandurlo** [comment]
Thanks :-) I will test my linux skills first to test it 😂

**Comment by Smandurlo** [comment]
@kovacsbalu I think I was able to follow your instructions (I am self impressed and pleased LOL) and it seems I get a proper route and time! I will try to replace the file in my HA in Portugal and report. Should I write here or somewhere else?
